"""add market signals table

Revision ID: 393f51c5b19e
Revises: e58da0933169
Create Date: 2026-06-25 17:25:48.814255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393f51c5b19e'
down_revision: Union[str, Sequence[str], None] = 'e58da0933169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_signals_article_id'), 'market_signals', ['article_id'], unique=True)
    op.create_index(op.f('ix_market_signals_company_id'), 'market_signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_market_signals_id'), 'market_signals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_signals_id'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_company_id'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_article_id'), table_name='market_signals')
    op.drop_table('market_signals')
    # ### end Alembic commands ###
